

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://cdn.pixabay.com/photo/2015/07/27/20/16/book-863418_960_720.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/Thiết-kế-n.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Binhminh Knowledge" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/Thiết-kế-n" # Site logo, also used in jekyll-seo-tag
url: "" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: 
email:
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
 
  250: '/assets/Thiết-kế-n@250px.png'
 
# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: About
  url: /elements/
- title: Blog
  url: /blog/
- title: More
  url: /categories/

navigation_footer:
- title: Education
  url: https://un.org

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Page: https://facebook.com/Binhminh-Knowledge-101354985447311
  Group: https://www.facebook.com/groups/1164302813983545


sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
